# Generated by Django 4.2.7 on 2025-07-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='id',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='message_id',
        ),
    ]
