apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
      version: green
  template:
    metadata:
      labels:
        app: django
        version: green
    spec:
      containers:
        - name: django
          image: localhost/cave254/django-messaging:0.0.2
          ports:
            - containerPort: 8000
